# Generated by Django 5.1.1 on 2024-09-18 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Student Name')),
                ('age', models.IntegerField(verbose_name='Student Age')),
                ('address', models.TextField(verbose_name='Student Address')),
            ],
        ),
    ]
